version: 2.1

commands: # all jobs/workflows use same commands
  set_version:
    steps:
      - checkout
      - run:
          name: set_version
          command: ./toolchain/stages/00-set_version.sh --latest --verbose
jobs:
  linux-x64:
    machine: # machine specifies a linux vm
      image: ubuntu-1604:201903-01
    resource_class: small
    steps:
      - set_version

workflows:
  build-basics: # this workflow will do mac, linux, and windows without arch xcompile
    jobs:
      - hold:
          type: approval
      - linux-x64:
          requires:
            - hold
